image: node:13.7

stages:
  - build
  - deploy

before_script:
  - node -v

cache:
  untracked: true
  paths:
    - node_modules/

before_script:
  - yarn

build:
  stage: build
  script:
    - STAGING=true yarn docusaurus parse
    - STAGING=true yarn docusaurus glossary
    - STAGING=true yarn build

pages:
  stage: deploy
  script:
    - STAGING=true yarn docusaurus parse
    - STAGING=true yarn docusaurus glossary
    - STAGING=true yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
