name: framework

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Run Terminology Design tools and deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Run Terminology Design tools
        run: bun run build:terminology

      - name: Build and Deploy
        run: |
          npx docusaurus build --out-dir build
          touch build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
